version: '3.8'

services:
  n8n-mw-order:
    image: n8nio/n8n:1.93.0
    container_name: n8n-mw-order
    restart: always
    env_file:
      - .env
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    ports:
      - "5679:5678"
    networks:
      - app-network
    depends_on:
      - postgres-mw-order
      - redis-mw-order
    volumes:
      - n8n_data:/home/node/.n8n
      - ./templates:/home/node/imports

  postgres-mw-order:
    image: postgres:15
    container_name: postgres-mw-order
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - n8n_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  redis-mw-order:
    image: redis:alpine
    container_name: n8n_redis-mw-order
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - n8n_redis_data:/data
    networks:
      - app-network

  caddy-mw-order:
    image: caddy:latest
    container_name: caddy-mw-order
    restart: always
    ports:
      - "5680:5680"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - n8n-mw-order
    networks:
      - app-network

volumes:
  n8n_data:
  n8n_redis_data:
  n8n_pg_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
